#!C:\WinP\bd39\bu\WPy64-3950\python-3.9.5.amd64\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
